# Cross-compiles the Windows build (beacom3d.exe) with MinGW-w64.
#   docker build -t beacom3d-win -f beacom3d_asm/Dockerfile.windows .
#   docker run --rm -v "${PWD}:/game" -w /game/beacom3d_asm beacom3d-win make windows
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update && apt-get -y install nasm make mingw-w64 curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/sdl
RUN curl -fsSL https://github.com/libsdl-org/SDL/releases/download/release-2.30.9/SDL2-devel-2.30.9-mingw.tar.gz | tar xz \
 && curl -fsSL https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.2/SDL2_image-devel-2.8.2-mingw.tar.gz | tar xz \
 && curl -fsSL https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.22.0/SDL2_ttf-devel-2.22.0-mingw.tar.gz | tar xz
