; GENERATED by tools/gen_win64_thunks.js -- do not edit by hand.
;
; System V -> Microsoft x64 calling-convention thunks for the Windows build.
; Each sv_NAME takes its arguments the Linux way (rdi, rsi, ..., xmm0..7),
; moves them to the Windows places (rcx/rdx/r8/r9 or xmm0..3 by position,
; the rest on the stack above 32 bytes of shadow space) and calls NAME.
; rbx, rbp and r12-r15 are preserved by both conventions, so nothing else
; needs saving on the way out. The two entry thunks at the bottom go the
; other way: Windows calls into our System V code.
default rel
section .text

global sv_scanf
extern scanf
; scanf(V)
sv_scanf:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov [rsp+48], rdi
    mov [rsp+56], rsi
    mov [rsp+64], rdx
    mov [rsp+72], rcx
    mov [rsp+80], r8
    mov [rsp+88], r9
    mov rcx, [rsp+48]
    mov rdx, [rsp+56]
    mov r8, [rsp+64]
    mov r9, [rsp+72]
    mov rax, [rsp+80]
    mov [rsp+32], rax
    mov rax, [rsp+88]
    mov [rsp+40], rax
    call scanf
    leave
    ret

global sv_puts
extern puts
; puts(i)
sv_puts:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call puts
    leave
    ret

global sv_putchar
extern putchar
; putchar(i)
sv_putchar:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call putchar
    leave
    ret

global sv_getchar
extern getchar
; getchar(void)
sv_getchar:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call getchar
    leave
    ret

global sv_system
extern system
; system(i)
sv_system:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call system
    leave
    ret

global sv_fopen
extern fopen
; fopen(ii)
sv_fopen:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call fopen
    leave
    ret

global sv_fread
extern fread
; fread(iiii)
sv_fread:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov [rsp+56], rcx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    mov r9, [rsp+56]
    call fread
    leave
    ret

global sv_fgetc
extern fgetc
; fgetc(i)
sv_fgetc:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call fgetc
    leave
    ret

global sv_fclose
extern fclose
; fclose(i)
sv_fclose:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call fclose
    leave
    ret

global sv_fflush
extern fflush
; fflush(i)
sv_fflush:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call fflush
    leave
    ret

global sv_fwrite
extern fwrite
; fwrite(iiii)
sv_fwrite:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov [rsp+56], rcx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    mov r9, [rsp+56]
    call fwrite
    leave
    ret

global sv_exit
extern exit
; exit(i)
sv_exit:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call exit
    leave
    ret

global sv_time
extern time
; time(i)
sv_time:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call time
    leave
    ret

global sv_getenv
extern getenv
; getenv(i)
sv_getenv:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call getenv
    leave
    ret

global sv_strstr
extern strstr
; strstr(ii)
sv_strstr:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call strstr
    leave
    ret

global sv_strlen
extern strlen
; strlen(i)
sv_strlen:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call strlen
    leave
    ret

global sv_memset
extern memset
; memset(iii)
sv_memset:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call memset
    leave
    ret

global sv_memcpy
extern memcpy
; memcpy(iii)
sv_memcpy:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call memcpy
    leave
    ret

global sv_sinf
extern sinf
; sinf(f)
sv_sinf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movss xmm0, [rsp+32]
    call sinf
    leave
    ret

global sv_cosf
extern cosf
; cosf(f)
sv_cosf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movss xmm0, [rsp+32]
    call cosf
    leave
    ret

global sv_sqrtf
extern sqrtf
; sqrtf(f)
sv_sqrtf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movss xmm0, [rsp+32]
    call sqrtf
    leave
    ret

global sv_expf
extern expf
; expf(f)
sv_expf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movss xmm0, [rsp+32]
    call expf
    leave
    ret

global sv_logf
extern logf
; logf(f)
sv_logf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movss xmm0, [rsp+32]
    call logf
    leave
    ret

global sv_tanf
extern tanf
; tanf(f)
sv_tanf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movss xmm0, [rsp+32]
    call tanf
    leave
    ret

global sv_powf
extern powf
; powf(ff)
sv_powf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    call powf
    leave
    ret

global sv_atan2f
extern atan2f
; atan2f(ff)
sv_atan2f:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    call atan2f
    leave
    ret

global sv_GetStdHandle
extern GetStdHandle
; GetStdHandle(i)
sv_GetStdHandle:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call GetStdHandle
    leave
    ret

global sv_GetConsoleMode
extern GetConsoleMode
; GetConsoleMode(ii)
sv_GetConsoleMode:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call GetConsoleMode
    leave
    ret

global sv_SetConsoleMode
extern SetConsoleMode
; SetConsoleMode(ii)
sv_SetConsoleMode:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call SetConsoleMode
    leave
    ret

global sv_SDL_Init
extern SDL_Init
; SDL_Init(i)
sv_SDL_Init:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_Init
    leave
    ret

global sv_SDL_Quit
extern SDL_Quit
; SDL_Quit(void)
sv_SDL_Quit:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call SDL_Quit
    leave
    ret

global sv_SDL_CreateWindow
extern SDL_CreateWindow
; SDL_CreateWindow(iiiiii)
sv_SDL_CreateWindow:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    mov [rsp+48], rdi
    mov [rsp+56], rsi
    mov [rsp+64], rdx
    mov [rsp+72], rcx
    mov [rsp+80], r8
    mov [rsp+88], r9
    mov rcx, [rsp+48]
    mov rdx, [rsp+56]
    mov r8, [rsp+64]
    mov r9, [rsp+72]
    mov rax, [rsp+80]
    mov [rsp+32], rax
    mov rax, [rsp+88]
    mov [rsp+40], rax
    call SDL_CreateWindow
    leave
    ret

global sv_SDL_DestroyWindow
extern SDL_DestroyWindow
; SDL_DestroyWindow(i)
sv_SDL_DestroyWindow:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_DestroyWindow
    leave
    ret

global sv_SDL_GL_SetAttribute
extern SDL_GL_SetAttribute
; SDL_GL_SetAttribute(ii)
sv_SDL_GL_SetAttribute:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call SDL_GL_SetAttribute
    leave
    ret

global sv_SDL_GL_CreateContext
extern SDL_GL_CreateContext
; SDL_GL_CreateContext(i)
sv_SDL_GL_CreateContext:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_GL_CreateContext
    leave
    ret

global sv_SDL_GL_SwapWindow
extern SDL_GL_SwapWindow
; SDL_GL_SwapWindow(i)
sv_SDL_GL_SwapWindow:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_GL_SwapWindow
    leave
    ret

global sv_SDL_GL_SetSwapInterval
extern SDL_GL_SetSwapInterval
; SDL_GL_SetSwapInterval(i)
sv_SDL_GL_SetSwapInterval:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_GL_SetSwapInterval
    leave
    ret

global sv_SDL_GL_GetProcAddress
extern SDL_GL_GetProcAddress
; SDL_GL_GetProcAddress(i)
sv_SDL_GL_GetProcAddress:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_GL_GetProcAddress
    leave
    ret

global sv_SDL_PollEvent
extern SDL_PollEvent
; SDL_PollEvent(i)
sv_SDL_PollEvent:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_PollEvent
    leave
    ret

global sv_SDL_GetKeyboardState
extern SDL_GetKeyboardState
; SDL_GetKeyboardState(i)
sv_SDL_GetKeyboardState:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_GetKeyboardState
    leave
    ret

global sv_SDL_SetRelativeMouseMode
extern SDL_SetRelativeMouseMode
; SDL_SetRelativeMouseMode(i)
sv_SDL_SetRelativeMouseMode:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_SetRelativeMouseMode
    leave
    ret

global sv_SDL_GetPerformanceCounter
extern SDL_GetPerformanceCounter
; SDL_GetPerformanceCounter(void)
sv_SDL_GetPerformanceCounter:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call SDL_GetPerformanceCounter
    leave
    ret

global sv_SDL_GetPerformanceFrequency
extern SDL_GetPerformanceFrequency
; SDL_GetPerformanceFrequency(void)
sv_SDL_GetPerformanceFrequency:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call SDL_GetPerformanceFrequency
    leave
    ret

global sv_SDL_Delay
extern SDL_Delay
; SDL_Delay(i)
sv_SDL_Delay:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_Delay
    leave
    ret

global sv_SDL_GetError
extern SDL_GetError
; SDL_GetError(void)
sv_SDL_GetError:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call SDL_GetError
    leave
    ret

global sv_SDL_ShowWindow
extern SDL_ShowWindow
; SDL_ShowWindow(i)
sv_SDL_ShowWindow:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_ShowWindow
    leave
    ret

global sv_SDL_HideWindow
extern SDL_HideWindow
; SDL_HideWindow(i)
sv_SDL_HideWindow:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_HideWindow
    leave
    ret

global sv_SDL_GetWindowSize
extern SDL_GetWindowSize
; SDL_GetWindowSize(iii)
sv_SDL_GetWindowSize:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call SDL_GetWindowSize
    leave
    ret

global sv_SDL_ConvertSurfaceFormat
extern SDL_ConvertSurfaceFormat
; SDL_ConvertSurfaceFormat(iii)
sv_SDL_ConvertSurfaceFormat:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call SDL_ConvertSurfaceFormat
    leave
    ret

global sv_SDL_FreeSurface
extern SDL_FreeSurface
; SDL_FreeSurface(i)
sv_SDL_FreeSurface:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_FreeSurface
    leave
    ret

global sv_SDL_CreateRGBSurfaceWithFormat
extern SDL_CreateRGBSurfaceWithFormat
; SDL_CreateRGBSurfaceWithFormat(iiiii)
sv_SDL_CreateRGBSurfaceWithFormat:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov [rsp+40], rdi
    mov [rsp+48], rsi
    mov [rsp+56], rdx
    mov [rsp+64], rcx
    mov [rsp+72], r8
    mov rcx, [rsp+40]
    mov rdx, [rsp+48]
    mov r8, [rsp+56]
    mov r9, [rsp+64]
    mov rax, [rsp+72]
    mov [rsp+32], rax
    call SDL_CreateRGBSurfaceWithFormat
    leave
    ret

global sv_SDL_UpperBlit
extern SDL_UpperBlit
; SDL_UpperBlit(iiii)
sv_SDL_UpperBlit:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov [rsp+56], rcx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    mov r9, [rsp+56]
    call SDL_UpperBlit
    leave
    ret

global sv_SDL_FillRect
extern SDL_FillRect
; SDL_FillRect(iii)
sv_SDL_FillRect:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call SDL_FillRect
    leave
    ret

global sv_SDL_SetWindowTitle
extern SDL_SetWindowTitle
; SDL_SetWindowTitle(ii)
sv_SDL_SetWindowTitle:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call SDL_SetWindowTitle
    leave
    ret

global sv_SDL_RaiseWindow
extern SDL_RaiseWindow
; SDL_RaiseWindow(i)
sv_SDL_RaiseWindow:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_RaiseWindow
    leave
    ret

global sv_SDL_SetWindowGrab
extern SDL_SetWindowGrab
; SDL_SetWindowGrab(ii)
sv_SDL_SetWindowGrab:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call SDL_SetWindowGrab
    leave
    ret

global sv_SDL_OpenAudioDevice
extern SDL_OpenAudioDevice
; SDL_OpenAudioDevice(iiiii)
sv_SDL_OpenAudioDevice:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov [rsp+40], rdi
    mov [rsp+48], rsi
    mov [rsp+56], rdx
    mov [rsp+64], rcx
    mov [rsp+72], r8
    mov rcx, [rsp+40]
    mov rdx, [rsp+48]
    mov r8, [rsp+56]
    mov r9, [rsp+64]
    mov rax, [rsp+72]
    mov [rsp+32], rax
    call SDL_OpenAudioDevice
    leave
    ret

global sv_SDL_PauseAudioDevice
extern SDL_PauseAudioDevice
; SDL_PauseAudioDevice(ii)
sv_SDL_PauseAudioDevice:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call SDL_PauseAudioDevice
    leave
    ret

global sv_SDL_LockAudioDevice
extern SDL_LockAudioDevice
; SDL_LockAudioDevice(i)
sv_SDL_LockAudioDevice:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_LockAudioDevice
    leave
    ret

global sv_SDL_UnlockAudioDevice
extern SDL_UnlockAudioDevice
; SDL_UnlockAudioDevice(i)
sv_SDL_UnlockAudioDevice:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_UnlockAudioDevice
    leave
    ret

global sv_SDL_SaveBMP_RW
extern SDL_SaveBMP_RW
; SDL_SaveBMP_RW(iii)
sv_SDL_SaveBMP_RW:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call SDL_SaveBMP_RW
    leave
    ret

global sv_SDL_RWFromFile
extern SDL_RWFromFile
; SDL_RWFromFile(ii)
sv_SDL_RWFromFile:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call SDL_RWFromFile
    leave
    ret

global sv_SDL_GetTicks
extern SDL_GetTicks
; SDL_GetTicks(void)
sv_SDL_GetTicks:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call SDL_GetTicks
    leave
    ret

global sv_SDL_WarpMouseInWindow
extern SDL_WarpMouseInWindow
; SDL_WarpMouseInWindow(iii)
sv_SDL_WarpMouseInWindow:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call SDL_WarpMouseInWindow
    leave
    ret

global sv_SDL_ShowCursor
extern SDL_ShowCursor
; SDL_ShowCursor(i)
sv_SDL_ShowCursor:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call SDL_ShowCursor
    leave
    ret

global sv_SDL_SetHint
extern SDL_SetHint
; SDL_SetHint(ii)
sv_SDL_SetHint:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call SDL_SetHint
    leave
    ret

global sv_IMG_Init
extern IMG_Init
; IMG_Init(i)
sv_IMG_Init:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call IMG_Init
    leave
    ret

global sv_IMG_Load
extern IMG_Load
; IMG_Load(i)
sv_IMG_Load:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call IMG_Load
    leave
    ret

global sv_TTF_Init
extern TTF_Init
; TTF_Init(void)
sv_TTF_Init:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call TTF_Init
    leave
    ret

global sv_TTF_OpenFont
extern TTF_OpenFont
; TTF_OpenFont(ii)
sv_TTF_OpenFont:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call TTF_OpenFont
    leave
    ret

global sv_TTF_RenderUTF8_Blended
extern TTF_RenderUTF8_Blended
; TTF_RenderUTF8_Blended(iii)
sv_TTF_RenderUTF8_Blended:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call TTF_RenderUTF8_Blended
    leave
    ret

global sv_TTF_RenderUTF8_Blended_Wrapped
extern TTF_RenderUTF8_Blended_Wrapped
; TTF_RenderUTF8_Blended_Wrapped(iiii)
sv_TTF_RenderUTF8_Blended_Wrapped:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov [rsp+56], rcx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    mov r9, [rsp+56]
    call TTF_RenderUTF8_Blended_Wrapped
    leave
    ret

global sv_glClear
extern glClear
; glClear(i)
sv_glClear:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glClear
    leave
    ret

global sv_glClearColor
extern glClearColor
; glClearColor(ffff)
sv_glClearColor:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movsd [rsp+48], xmm2
    movsd [rsp+56], xmm3
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    movss xmm2, [rsp+48]
    movss xmm3, [rsp+56]
    call glClearColor
    leave
    ret

global sv_glEnable
extern glEnable
; glEnable(i)
sv_glEnable:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glEnable
    leave
    ret

global sv_glDisable
extern glDisable
; glDisable(i)
sv_glDisable:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glDisable
    leave
    ret

global sv_glBlendFunc
extern glBlendFunc
; glBlendFunc(ii)
sv_glBlendFunc:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glBlendFunc
    leave
    ret

global sv_glViewport
extern glViewport
; glViewport(iiii)
sv_glViewport:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov [rsp+56], rcx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    mov r9, [rsp+56]
    call glViewport
    leave
    ret

global sv_glMatrixMode
extern glMatrixMode
; glMatrixMode(i)
sv_glMatrixMode:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glMatrixMode
    leave
    ret

global sv_glLoadIdentity
extern glLoadIdentity
; glLoadIdentity(void)
sv_glLoadIdentity:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call glLoadIdentity
    leave
    ret

global sv_glFrustum
extern glFrustum
; glFrustum(dddddd)
sv_glFrustum:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    movsd [rsp+48], xmm0
    movsd [rsp+56], xmm1
    movsd [rsp+64], xmm2
    movsd [rsp+72], xmm3
    movsd [rsp+80], xmm4
    movsd [rsp+88], xmm5
    movsd xmm0, [rsp+48]
    movsd xmm1, [rsp+56]
    movsd xmm2, [rsp+64]
    movsd xmm3, [rsp+72]
    mov rax, [rsp+80]
    mov [rsp+32], rax
    mov rax, [rsp+88]
    mov [rsp+40], rax
    call glFrustum
    leave
    ret

global sv_glOrtho
extern glOrtho
; glOrtho(dddddd)
sv_glOrtho:
    push rbp
    mov rbp, rsp
    sub rsp, 96
    movsd [rsp+48], xmm0
    movsd [rsp+56], xmm1
    movsd [rsp+64], xmm2
    movsd [rsp+72], xmm3
    movsd [rsp+80], xmm4
    movsd [rsp+88], xmm5
    movsd xmm0, [rsp+48]
    movsd xmm1, [rsp+56]
    movsd xmm2, [rsp+64]
    movsd xmm3, [rsp+72]
    mov rax, [rsp+80]
    mov [rsp+32], rax
    mov rax, [rsp+88]
    mov [rsp+40], rax
    call glOrtho
    leave
    ret

global sv_glRotatef
extern glRotatef
; glRotatef(ffff)
sv_glRotatef:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movsd [rsp+48], xmm2
    movsd [rsp+56], xmm3
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    movss xmm2, [rsp+48]
    movss xmm3, [rsp+56]
    call glRotatef
    leave
    ret

global sv_glTranslatef
extern glTranslatef
; glTranslatef(fff)
sv_glTranslatef:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movsd [rsp+48], xmm2
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    movss xmm2, [rsp+48]
    call glTranslatef
    leave
    ret

global sv_glBegin
extern glBegin
; glBegin(i)
sv_glBegin:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glBegin
    leave
    ret

global sv_glEnd
extern glEnd
; glEnd(void)
sv_glEnd:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call glEnd
    leave
    ret

global sv_glVertex3f
extern glVertex3f
; glVertex3f(fff)
sv_glVertex3f:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movsd [rsp+48], xmm2
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    movss xmm2, [rsp+48]
    call glVertex3f
    leave
    ret

global sv_glVertex2f
extern glVertex2f
; glVertex2f(ff)
sv_glVertex2f:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    call glVertex2f
    leave
    ret

global sv_glNormal3f
extern glNormal3f
; glNormal3f(fff)
sv_glNormal3f:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movsd [rsp+48], xmm2
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    movss xmm2, [rsp+48]
    call glNormal3f
    leave
    ret

global sv_glTexCoord2f
extern glTexCoord2f
; glTexCoord2f(ff)
sv_glTexCoord2f:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    call glTexCoord2f
    leave
    ret

global sv_glColor4f
extern glColor4f
; glColor4f(ffff)
sv_glColor4f:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movsd [rsp+48], xmm2
    movsd [rsp+56], xmm3
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    movss xmm2, [rsp+48]
    movss xmm3, [rsp+56]
    call glColor4f
    leave
    ret

global sv_glColor3f
extern glColor3f
; glColor3f(fff)
sv_glColor3f:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movsd [rsp+48], xmm2
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    movss xmm2, [rsp+48]
    call glColor3f
    leave
    ret

global sv_glGenTextures
extern glGenTextures
; glGenTextures(ii)
sv_glGenTextures:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glGenTextures
    leave
    ret

global sv_glBindTexture
extern glBindTexture
; glBindTexture(ii)
sv_glBindTexture:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glBindTexture
    leave
    ret

global sv_glTexImage2D
extern glTexImage2D
; glTexImage2D(iiiiiiiii)
sv_glTexImage2D:
    push rbp
    mov rbp, rsp
    sub rsp, 144
    mov [rsp+72], rdi
    mov [rsp+80], rsi
    mov [rsp+88], rdx
    mov [rsp+96], rcx
    mov [rsp+104], r8
    mov [rsp+112], r9
    mov rax, [rbp+16]
    mov [rsp+120], rax
    mov rax, [rbp+24]
    mov [rsp+128], rax
    mov rax, [rbp+32]
    mov [rsp+136], rax
    mov rcx, [rsp+72]
    mov rdx, [rsp+80]
    mov r8, [rsp+88]
    mov r9, [rsp+96]
    mov rax, [rsp+104]
    mov [rsp+32], rax
    mov rax, [rsp+112]
    mov [rsp+40], rax
    mov rax, [rsp+120]
    mov [rsp+48], rax
    mov rax, [rsp+128]
    mov [rsp+56], rax
    mov rax, [rsp+136]
    mov [rsp+64], rax
    call glTexImage2D
    leave
    ret

global sv_glTexParameteri
extern glTexParameteri
; glTexParameteri(iii)
sv_glTexParameteri:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call glTexParameteri
    leave
    ret

global sv_glPixelStorei
extern glPixelStorei
; glPixelStorei(ii)
sv_glPixelStorei:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glPixelStorei
    leave
    ret

global sv_glGenLists
extern glGenLists
; glGenLists(i)
sv_glGenLists:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glGenLists
    leave
    ret

global sv_glNewList
extern glNewList
; glNewList(ii)
sv_glNewList:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glNewList
    leave
    ret

global sv_glEndList
extern glEndList
; glEndList(void)
sv_glEndList:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call glEndList
    leave
    ret

global sv_glCallList
extern glCallList
; glCallList(i)
sv_glCallList:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glCallList
    leave
    ret

global sv_glFogi
extern glFogi
; glFogi(ii)
sv_glFogi:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glFogi
    leave
    ret

global sv_glFogf
extern glFogf
; glFogf(if)
sv_glFogf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    movsd [rsp+40], xmm0
    mov rcx, [rsp+32]
    movss xmm1, [rsp+40]
    call glFogf
    leave
    ret

global sv_glFogfv
extern glFogfv
; glFogfv(ii)
sv_glFogfv:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glFogfv
    leave
    ret

global sv_glDeleteTextures
extern glDeleteTextures
; glDeleteTextures(ii)
sv_glDeleteTextures:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glDeleteTextures
    leave
    ret

global sv_glDepthMask
extern glDepthMask
; glDepthMask(i)
sv_glDepthMask:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glDepthMask
    leave
    ret

global sv_glAlphaFunc
extern glAlphaFunc
; glAlphaFunc(if)
sv_glAlphaFunc:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    movsd [rsp+40], xmm0
    mov rcx, [rsp+32]
    movss xmm1, [rsp+40]
    call glAlphaFunc
    leave
    ret

global sv_glReadPixels
extern glReadPixels
; glReadPixels(iiiiiii)
sv_glReadPixels:
    push rbp
    mov rbp, rsp
    sub rsp, 112
    mov [rsp+56], rdi
    mov [rsp+64], rsi
    mov [rsp+72], rdx
    mov [rsp+80], rcx
    mov [rsp+88], r8
    mov [rsp+96], r9
    mov rax, [rbp+16]
    mov [rsp+104], rax
    mov rcx, [rsp+56]
    mov rdx, [rsp+64]
    mov r8, [rsp+72]
    mov r9, [rsp+80]
    mov rax, [rsp+88]
    mov [rsp+32], rax
    mov rax, [rsp+96]
    mov [rsp+40], rax
    mov rax, [rsp+104]
    mov [rsp+48], rax
    call glReadPixels
    leave
    ret

global sv_glFinish
extern glFinish
; glFinish(void)
sv_glFinish:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call glFinish
    leave
    ret

global sv_glGetError
extern glGetError
; glGetError(void)
sv_glGetError:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call glGetError
    leave
    ret

global sv_glPushMatrix
extern glPushMatrix
; glPushMatrix(void)
sv_glPushMatrix:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call glPushMatrix
    leave
    ret

global sv_glPopMatrix
extern glPopMatrix
; glPopMatrix(void)
sv_glPopMatrix:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call glPopMatrix
    leave
    ret

global sv_glMultMatrixf
extern glMultMatrixf
; glMultMatrixf(i)
sv_glMultMatrixf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glMultMatrixf
    leave
    ret

global sv_glDeleteLists
extern glDeleteLists
; glDeleteLists(ii)
sv_glDeleteLists:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glDeleteLists
    leave
    ret

global sv_glCopyTexSubImage2D
extern glCopyTexSubImage2D
; glCopyTexSubImage2D(iiiiiiii)
sv_glCopyTexSubImage2D:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rsp+64], rdi
    mov [rsp+72], rsi
    mov [rsp+80], rdx
    mov [rsp+88], rcx
    mov [rsp+96], r8
    mov [rsp+104], r9
    mov rax, [rbp+16]
    mov [rsp+112], rax
    mov rax, [rbp+24]
    mov [rsp+120], rax
    mov rcx, [rsp+64]
    mov rdx, [rsp+72]
    mov r8, [rsp+80]
    mov r9, [rsp+88]
    mov rax, [rsp+96]
    mov [rsp+32], rax
    mov rax, [rsp+104]
    mov [rsp+40], rax
    mov rax, [rsp+112]
    mov [rsp+48], rax
    mov rax, [rsp+120]
    mov [rsp+56], rax
    call glCopyTexSubImage2D
    leave
    ret

global sv_glGetString
extern glGetString
; glGetString(i)
sv_glGetString:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glGetString
    leave
    ret

global sv_glLoadMatrixf
extern glLoadMatrixf
; glLoadMatrixf(i)
sv_glLoadMatrixf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glLoadMatrixf
    leave
    ret

global sv_glColorMask
extern glColorMask
; glColorMask(iiii)
sv_glColorMask:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov [rsp+56], rcx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    mov r9, [rsp+56]
    call glColorMask
    leave
    ret

global sv_glPolygonOffset
extern glPolygonOffset
; glPolygonOffset(ff)
sv_glPolygonOffset:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movss xmm0, [rsp+32]
    movss xmm1, [rsp+40]
    call glPolygonOffset
    leave
    ret

global sv_glDrawBuffer
extern glDrawBuffer
; glDrawBuffer(i)
sv_glDrawBuffer:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glDrawBuffer
    leave
    ret

global sv_glReadBuffer
extern glReadBuffer
; glReadBuffer(i)
sv_glReadBuffer:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glReadBuffer
    leave
    ret

global sv_glTexParameterf
extern glTexParameterf
; glTexParameterf(iif)
sv_glTexParameterf:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    movsd [rsp+48], xmm0
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    movss xmm2, [rsp+48]
    call glTexParameterf
    leave
    ret

global sv_glStencilFunc
extern glStencilFunc
; glStencilFunc(iii)
sv_glStencilFunc:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call glStencilFunc
    leave
    ret

global sv_glStencilOp
extern glStencilOp
; glStencilOp(iii)
sv_glStencilOp:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call glStencilOp
    leave
    ret

global sv_glStencilMask
extern glStencilMask
; glStencilMask(i)
sv_glStencilMask:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glStencilMask
    leave
    ret

global sv_glClearStencil
extern glClearStencil
; glClearStencil(i)
sv_glClearStencil:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glClearStencil
    leave
    ret

global sv_glDepthFunc
extern glDepthFunc
; glDepthFunc(i)
sv_glDepthFunc:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call glDepthFunc
    leave
    ret

global sv_glDepthRange
extern glDepthRange
; glDepthRange(dd)
sv_glDepthRange:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    movsd [rsp+32], xmm0
    movsd [rsp+40], xmm1
    movsd xmm0, [rsp+32]
    movsd xmm1, [rsp+40]
    call glDepthRange
    leave
    ret

global sv_glClipPlane
extern glClipPlane
; glClipPlane(ii)
sv_glClipPlane:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glClipPlane
    leave
    ret

global sv_glGetFloatv
extern glGetFloatv
; glGetFloatv(ii)
sv_glGetFloatv:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call glGetFloatv
    leave
    ret

global sv_p_glCreateShader
extern p_glCreateShader
; (*p_glCreateShader)(i)
sv_p_glCreateShader:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call [p_glCreateShader]
    leave
    ret

global sv_p_glShaderSource
extern p_glShaderSource
; (*p_glShaderSource)(iiii)
sv_p_glShaderSource:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov [rsp+56], rcx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    mov r9, [rsp+56]
    call [p_glShaderSource]
    leave
    ret

global sv_p_glCompileShader
extern p_glCompileShader
; (*p_glCompileShader)(i)
sv_p_glCompileShader:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call [p_glCompileShader]
    leave
    ret

global sv_p_glGetShaderiv
extern p_glGetShaderiv
; (*p_glGetShaderiv)(iii)
sv_p_glGetShaderiv:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call [p_glGetShaderiv]
    leave
    ret

global sv_p_glGetShaderInfoLog
extern p_glGetShaderInfoLog
; (*p_glGetShaderInfoLog)(iiii)
sv_p_glGetShaderInfoLog:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov [rsp+56], rcx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    mov r9, [rsp+56]
    call [p_glGetShaderInfoLog]
    leave
    ret

global sv_p_glCreateProgram
extern p_glCreateProgram
; (*p_glCreateProgram)(void)
sv_p_glCreateProgram:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    call [p_glCreateProgram]
    leave
    ret

global sv_p_glAttachShader
extern p_glAttachShader
; (*p_glAttachShader)(ii)
sv_p_glAttachShader:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call [p_glAttachShader]
    leave
    ret

global sv_p_glLinkProgram
extern p_glLinkProgram
; (*p_glLinkProgram)(i)
sv_p_glLinkProgram:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call [p_glLinkProgram]
    leave
    ret

global sv_p_glUseProgram
extern p_glUseProgram
; (*p_glUseProgram)(i)
sv_p_glUseProgram:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call [p_glUseProgram]
    leave
    ret

global sv_p_glGetUniformLocation
extern p_glGetUniformLocation
; (*p_glGetUniformLocation)(ii)
sv_p_glGetUniformLocation:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call [p_glGetUniformLocation]
    leave
    ret

global sv_p_glUniform1f
extern p_glUniform1f
; (*p_glUniform1f)(if)
sv_p_glUniform1f:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    movsd [rsp+40], xmm0
    mov rcx, [rsp+32]
    movss xmm1, [rsp+40]
    call [p_glUniform1f]
    leave
    ret

global sv_p_glUniform1i
extern p_glUniform1i
; (*p_glUniform1i)(ii)
sv_p_glUniform1i:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call [p_glUniform1i]
    leave
    ret

global sv_p_glUniform3f
extern p_glUniform3f
; (*p_glUniform3f)(ifff)
sv_p_glUniform3f:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    movsd [rsp+40], xmm0
    movsd [rsp+48], xmm1
    movsd [rsp+56], xmm2
    mov rcx, [rsp+32]
    movss xmm1, [rsp+40]
    movss xmm2, [rsp+48]
    movss xmm3, [rsp+56]
    call [p_glUniform3f]
    leave
    ret

global sv_p_glUniform3fv
extern p_glUniform3fv
; (*p_glUniform3fv)(iii)
sv_p_glUniform3fv:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    call [p_glUniform3fv]
    leave
    ret

global sv_p_glUniformMatrix4fv
extern p_glUniformMatrix4fv
; (*p_glUniformMatrix4fv)(iiii)
sv_p_glUniformMatrix4fv:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov [rsp+56], rcx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    mov r9, [rsp+56]
    call [p_glUniformMatrix4fv]
    leave
    ret

global sv_p_glGetProgramInfoLog
extern p_glGetProgramInfoLog
; (*p_glGetProgramInfoLog)(iiii)
sv_p_glGetProgramInfoLog:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov [rsp+48], rdx
    mov [rsp+56], rcx
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    mov r8, [rsp+48]
    mov r9, [rsp+56]
    call [p_glGetProgramInfoLog]
    leave
    ret

global sv_p_glGenFramebuffers
extern p_glGenFramebuffers
; (*p_glGenFramebuffers)(ii)
sv_p_glGenFramebuffers:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call [p_glGenFramebuffers]
    leave
    ret

global sv_p_glBindFramebuffer
extern p_glBindFramebuffer
; (*p_glBindFramebuffer)(ii)
sv_p_glBindFramebuffer:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov [rsp+40], rsi
    mov rcx, [rsp+32]
    mov rdx, [rsp+40]
    call [p_glBindFramebuffer]
    leave
    ret

global sv_p_glFramebufferTexture2D
extern p_glFramebufferTexture2D
; (*p_glFramebufferTexture2D)(iiiii)
sv_p_glFramebufferTexture2D:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov [rsp+40], rdi
    mov [rsp+48], rsi
    mov [rsp+56], rdx
    mov [rsp+64], rcx
    mov [rsp+72], r8
    mov rcx, [rsp+40]
    mov rdx, [rsp+48]
    mov r8, [rsp+56]
    mov r9, [rsp+64]
    mov rax, [rsp+72]
    mov [rsp+32], rax
    call [p_glFramebufferTexture2D]
    leave
    ret

global sv_p_glCheckFramebufferStatus
extern p_glCheckFramebufferStatus
; (*p_glCheckFramebufferStatus)(i)
sv_p_glCheckFramebufferStatus:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call [p_glCheckFramebufferStatus]
    leave
    ret

global sv_p_glActiveTexture
extern p_glActiveTexture
; (*p_glActiveTexture)(i)
sv_p_glActiveTexture:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov [rsp+32], rdi
    mov rcx, [rsp+32]
    call [p_glActiveTexture]
    leave
    ret

global sv_printf
extern printf
; printf(i, ...) -- walks the format string: each %f/%e/%g
; conversion takes the next xmm register, every other conversion the next
; integer register; then everything is laid out by position for Windows
; (variadic doubles travel in integer registers/stack slots there).
sv_printf:
    push rbp
    mov rbp, rsp
    sub rsp, 368
    ; [rsp+0..31] shadow, [rsp+32..127] stack args, [rsp+128..255] A[16]
    ; (the Windows argument list), [rsp+256..] free integer regs, [rsp+304..] xmm0..7
    mov [rsp+128], rdi
    mov [rsp+256], rsi
    mov [rsp+264], rdx
    mov [rsp+272], rcx
    mov [rsp+280], r8
    mov [rsp+288], r9
    movsd [rsp+304], xmm0
    movsd [rsp+312], xmm1
    movsd [rsp+320], xmm2
    movsd [rsp+328], xmm3
    movsd [rsp+336], xmm4
    movsd [rsp+344], xmm5
    movsd [rsp+352], xmm6
    movsd [rsp+360], xmm7
    mov r10, rdi             ; format string
    mov r11d, 1                    ; next position in A
    xor ecx, ecx                        ; integer values used
    xor edx, edx                        ; float values used
.scan:
    movzx eax, byte [r10]
    test eax, eax
    jz .scanned
    inc r10
    cmp eax, '%'
    jne .scan
.spec:
    movzx eax, byte [r10]
    test eax, eax
    jz .scanned
    inc r10
    cmp eax, '%'
    je .scan                            ; "%%" is a literal percent sign
    ; skip flags, width, precision and length modifiers
    cmp eax, '9'
    jbe .spec
    cmp eax, 'l'
    je .spec
    cmp eax, 'h'
    je .spec
    cmp eax, 'L'
    je .spec
    cmp eax, 'z'
    je .spec
    ; a conversion character
    cmp eax, 'f'
    je .flt
    cmp eax, 'e'
    je .flt
    cmp eax, 'g'
    je .flt
    cmp eax, 'F'
    je .flt
    cmp eax, 'E'
    je .flt
    cmp eax, 'G'
    je .flt
    mov rax, [rsp+256+rcx*8]
    inc ecx
    jmp .store
.flt:
    mov rax, [rsp+304+rdx*8]
    inc edx
.store:
    cmp r11d, 16
    jge .scan
    mov [rsp+128+r11*8], rax
    inc r11d
    jmp .scan
.scanned:
    ; positions 4.. go on the stack above the shadow space
    mov ecx, 4
.stk:
    cmp ecx, r11d
    jge .regs
    mov rax, [rsp+128+rcx*8]
    mov [rsp+32+rcx*8-32], rax
    inc ecx
    jmp .stk
.regs:
    mov rcx, [rsp+128]
    mov rdx, [rsp+136]
    mov r8, [rsp+144]
    mov r9, [rsp+152]
    movq xmm0, rcx
    movq xmm1, rdx
    movq xmm2, r8
    movq xmm3, r9
    call printf
    leave
    ret

global sv_snprintf
extern snprintf
; snprintf(iii, ...) -- walks the format string: each %f/%e/%g
; conversion takes the next xmm register, every other conversion the next
; integer register; then everything is laid out by position for Windows
; (variadic doubles travel in integer registers/stack slots there).
sv_snprintf:
    push rbp
    mov rbp, rsp
    sub rsp, 368
    ; [rsp+0..31] shadow, [rsp+32..127] stack args, [rsp+128..255] A[16]
    ; (the Windows argument list), [rsp+256..] free integer regs, [rsp+304..] xmm0..7
    mov [rsp+128], rdi
    mov [rsp+136], rsi
    mov [rsp+144], rdx
    mov [rsp+256], rcx
    mov [rsp+264], r8
    mov [rsp+272], r9
    movsd [rsp+304], xmm0
    movsd [rsp+312], xmm1
    movsd [rsp+320], xmm2
    movsd [rsp+328], xmm3
    movsd [rsp+336], xmm4
    movsd [rsp+344], xmm5
    movsd [rsp+352], xmm6
    movsd [rsp+360], xmm7
    mov r10, rdx             ; format string
    mov r11d, 3                    ; next position in A
    xor ecx, ecx                        ; integer values used
    xor edx, edx                        ; float values used
.scan:
    movzx eax, byte [r10]
    test eax, eax
    jz .scanned
    inc r10
    cmp eax, '%'
    jne .scan
.spec:
    movzx eax, byte [r10]
    test eax, eax
    jz .scanned
    inc r10
    cmp eax, '%'
    je .scan                            ; "%%" is a literal percent sign
    ; skip flags, width, precision and length modifiers
    cmp eax, '9'
    jbe .spec
    cmp eax, 'l'
    je .spec
    cmp eax, 'h'
    je .spec
    cmp eax, 'L'
    je .spec
    cmp eax, 'z'
    je .spec
    ; a conversion character
    cmp eax, 'f'
    je .flt
    cmp eax, 'e'
    je .flt
    cmp eax, 'g'
    je .flt
    cmp eax, 'F'
    je .flt
    cmp eax, 'E'
    je .flt
    cmp eax, 'G'
    je .flt
    mov rax, [rsp+256+rcx*8]
    inc ecx
    jmp .store
.flt:
    mov rax, [rsp+304+rdx*8]
    inc edx
.store:
    cmp r11d, 16
    jge .scan
    mov [rsp+128+r11*8], rax
    inc r11d
    jmp .scan
.scanned:
    ; positions 4.. go on the stack above the shadow space
    mov ecx, 4
.stk:
    cmp ecx, r11d
    jge .regs
    mov rax, [rsp+128+rcx*8]
    mov [rsp+32+rcx*8-32], rax
    inc ecx
    jmp .stk
.regs:
    mov rcx, [rsp+128]
    mov rdx, [rsp+136]
    mov r8, [rsp+144]
    mov r9, [rsp+152]
    movq xmm0, rcx
    movq xmm1, rdx
    movq xmm2, r8
    movq xmm3, r9
    call snprintf
    leave
    ret


; ---- Windows -> System V entry points -------------------------------------------
; Windows expects rdi, rsi and xmm6-xmm15 to survive a call; System V code
; treats them as scratch, so these wrappers save and restore them.
%macro SAVE_WIN_REGS 0
    push rbp
    mov rbp, rsp
    push rdi
    push rsi
    sub rsp, 160
    movdqu [rsp+0], xmm6
    movdqu [rsp+16], xmm7
    movdqu [rsp+32], xmm8
    movdqu [rsp+48], xmm9
    movdqu [rsp+64], xmm10
    movdqu [rsp+80], xmm11
    movdqu [rsp+96], xmm12
    movdqu [rsp+112], xmm13
    movdqu [rsp+128], xmm14
    movdqu [rsp+144], xmm15
%endmacro
%macro RESTORE_WIN_REGS 0
    movdqu xmm6, [rsp+0]
    movdqu xmm7, [rsp+16]
    movdqu xmm8, [rsp+32]
    movdqu xmm9, [rsp+48]
    movdqu xmm10, [rsp+64]
    movdqu xmm11, [rsp+80]
    movdqu xmm12, [rsp+96]
    movdqu xmm13, [rsp+112]
    movdqu xmm14, [rsp+128]
    movdqu xmm15, [rsp+144]
    add rsp, 160
    pop rsi
    pop rdi
    pop rbp
%endmacro

; int SDL_main(int argc, char **argv) -- called by SDL2main's real main()
global SDL_main
extern beacom_main
SDL_main:
    SAVE_WIN_REGS
    mov edi, ecx
    mov rsi, rdx
    call beacom_main
    RESTORE_WIN_REGS
    ret

; void audio_cb_win64(void *userdata, Uint8 *stream, int len) -- SDL audio thread
global audio_cb_win64
extern audio_cb
audio_cb_win64:
    SAVE_WIN_REGS
    mov rdi, rcx
    mov rsi, rdx
    mov edx, r8d
    call audio_cb
    RESTORE_WIN_REGS
    ret
